name: "Bump version and release"

# Run only on closed Pull Requests targeting the main branch, and has changes in files or folders in the packages folders.
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - packages/midt/**
      - packages/components/**
      - packages/map-template/**
      - packages/react-components/**
      - .github/workflows/bump-version-release.yml

jobs:
  check-labels:
    name: "Check Pull Request Labels"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mheap/github-action-required-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"

  midt-release-npm:
    name: Release MIDT to npm
    needs: check-labels
    outputs:
      has_changed_files: ${{ steps.changed-files-midt.outputs.any_changed }}
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files in the midt folder
        id: changed-files-midt
        uses: tj-actions/changed-files@v41

  gcp-deploy:
    name: Deploy to GCP
    needs: midt-release-npm
    runs-on: ubuntu-latest
    if: ${{ needs.midt-release-npm.outputs.has_changed_files == 'true' }}
    env:
      GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL || '' }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY || '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate with GCP
        run: |
          echo "$GCP_SA_KEY" > gcp-key.json
          gcloud auth activate-service-account "$GCP_SA_EMAIL" --key-file=gcp-key.json
          rm gcp-key.json
